feat(devops-66): update nginx & modsecurity-crs version
mission-apprentissage/infra pull request #48
Opened 2024-07-11 08:05 UTC by kevbarns

- https://tableaudebord-apprentissage.atlassian.net/browse/DEVOPS-66

version nginx : https://hub.docker.com/layers/library/nginx/1.27.0/images/sha256-db5e49f40979ce521f05f0bc9f513d0abacce47904e229f3a95c2e6d9b47f244?context=explore

version modsec :  https://hub.docker.com/layers/owasp/modsecurity-crs/4.3.0-nginx-202406090906/images/sha256-b9fdfb3b6e521eb2171295c8852ee9b58975fb7766f60f015789358e827de5f8?context=explore

2024-07-11 10:08 UTC, moroine commented
https://github.com/coreruleset/coreruleset/releases/tag/v4.0.0

2024-07-11 10:40 UTC, moroine commented
Alors la modification du Dockerfile ne déclanche pas de release auto.

Il faut lancer `.bin/mna release:proxy` avec une version beta dans un premier temps. Ensuite il faut modifier le `env.ini` du produit pour utiliser la nouvelle version.

Une fois testée et validée tu peux faire une nouvelle release

2024-07-31 14:12 UTC, kevbarns commented
Notes : mise à jour manuel obligatoire `sudo chown -R 101:101 system/nginx/`

2024-10-02 12:18 UTC, moroine commented
@kevbarns status de cette PR ?

2024-10-08 11:46 UTC, moroine requested changes
@kevbarns je te laisses request une review quand c'est pret

2024-10-08 13:57 UTC, kevbarns commented
Sur cette PR il me faut de l'aide comme discuté sur slack @moroine

2024-12-20 11:50 UTC, moroine approved these changes

2024-12-20 11:54 UTC, merged