feat(devops-84): add kernel configuration
mission-apprentissage/infra pull request #81
Opened 2024-10-07 16:54 UTC by kevbarns

https://tableaudebord-apprentissage.atlassian.net/browse/DEVOPS-84
--> a tester sur VPS dédié

2024-10-08 11:42 UTC, moroine reviewed
@kevbarns tu peux ajouter les demandes de review quand c'est terminé ?

2024-10-08 12:11 UTC, kevbarns commented
@moroine testé et validé avec le template-apprentissage sur un environnement sandbox, le setup va jusqu'au bout avec un fail sur le setup des notifications slack  `send-to-slack.sh.jinja2` (pas de clé dans le vault).

2024-10-16 09:22 UTC, moroine approved these changes

2024-10-16 09:26 UTC, kevbarns commented
PR en test : 
- A déployer manuellement sur les env de recette (LBA/BAL)

2024-11-04 09:24 UTC, kevbarns commented
mettre `add_kernel_modification` à false partout ailleurs

2024-12-03 10:23 UTC, kevbarns commented
test effectué sur le pentest ✅

2024-12-12 15:08 UTC, antoinebigard requested changes
Comme discuté avec @kevbarns, pas chaud de garder add_kernel_modification=false

ça va être devenir un vieux legacy pas beaux 
@moroine

2024-12-13 14:01 UTC, moroine commented
Je pense que ce flag peut etre remove dans un mois une fois validé et testé en prod LBA. Apres si vous etes serein sur vos changements let's go

2024-12-13 14:48 UTC, kevbarns commented
c'est sur le pentest depuis 10 jours là, on peut attendre d'avantage si vous le souhaitez, je ne constate pas de problème depuis.

2024-12-16 08:18 UTC, moroine commented
Let's do then

2024-12-20 12:22 UTC, antoinebigard approved these changes

2024-12-20 12:34 UTC, antoinebigard commented
Finalement changement d'avis sur la variable car il y a dautre serveurs exemple : VPN, mongo, data

2024-12-20 12:37 UTC, merged