feat: change bin name from mna to infra
mission-apprentissage/infra pull request #97
Opened 2024-11-20 11:04 UTC by antoinebigard

2024-11-20 14:49 UTC, moroine requested changes

2024-11-20 14:49 UTC, moroine commented on .bin/commands.sh
> +  sudo ln -fs "${ROOT_DIR}/.bin/infra" "/usr/local/bin/infra"
T'es sur de toi la dessus ? Du coup tu peux pas avoir plusieurs `infra` installé ? Pour moi il faut absoluement prefix pour l'installation systeme

2024-11-21 08:21 UTC, antoinebigard commented on .bin/commands.sh
> +  sudo ln -fs "${ROOT_DIR}/.bin/infra" "/usr/local/bin/infra"
Idéalement dans les changements d'après on rend l'infra le plus générique possible. l'idée étant dans avoir une seule après perso je m'en sers pas de ce truc

2024-11-21 09:29 UTC, antoinebigard commented on .bin/commands.sh
> +  sudo ln -fs "${ROOT_DIR}/.bin/infra" "/usr/local/bin/infra"
🤷‍♂️

2024-11-21 15:50 UTC, moroine approved these changes

2024-11-22 11:12 UTC, merged